// Categories
export const IS_FETCHING_CATEGORIES = 'IS_FETCHING_CATEGORIES';
export const RECEIVED_CATEGORIES = 'RECEIVED_CATEGORIES';

// Posts
export const IS_FETCHING_POSTS = 'IS_FETCHING_POSTS';
export const RECEIVED_POSTS = 'RECEIVED_POSTS';
export const IS_FETCHING_POST = 'IS_FETCHING_POST';
export const RECEIVED_POST = 'RECEIVED_POST';
export const IS_SENDING_POST = 'IS_SENDING_POST';
export const SAVED_POST = 'SAVED_POST';
export const EDITED_POST = 'EDITED_POST';
export const DELETED_POST = 'DELETED_POST';
export const SORT_POSTS = 'SORT_POSTS';

// Comments
export const IS_FETCHING_COMMENT = 'IS_FETCHING_COMMENT';
export const RECEIVED_COMMENT = 'RECEIVED_COMMENT';
export const IS_FETCHING_COMMENTS = 'IS_FETCHING_COMMENTS';
export const RECEIVED_COMMENTS = 'RECEIVED_COMMENTS';
export const IS_SENDING_COMMENT = 'IS_SENDING_COMMENT';
export const SAVED_COMMENT = 'SAVED_COMMENT';
export const EDITED_COMMENT = 'EDITED_COMMENT';
export const DELETED_COMMENT = 'DELETED_COMMENT';

// Posts from Category
export const IS_FETCHING_CATEGORY_POSTS = 'IS_FETCHING_CATEGORY_POSTS';
export const RECEIVED_CATEGORY_POSTS = 'RECEIVED_CATEGORY_POSTS';

// Comments from Posts
export const IS_FETCHING_POSTS_COMMENTS = 'IS_FETCHING_POSTS_COMMENTS';
export const RECEIVED_POSTS_COMMENTS = 'RECEIVED_POSTS_COMMENTS';
